spring.application.name=instagram_clone
# Application Port
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/instagramclone?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Cloudinary Config
cloudinary.cloud_name=dr0yboilf
cloudinary.api_key=824826181893878
cloudinary.api_secret=6o4jYcm_1307ECkXiPBs9YpoDfY

# Allow up to 100MB for file uploads
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


