spring.application.name=instagram_clone
# Application Port
server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/instagramclone?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Cloudinary Config
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:your_cloudinary_cloud_name}
cloudinary.api_key=${CLOUDINARY_API_KEY:your_cloudinary_api_key}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:your_cloudinary_api_secret}

# Allow up to 100MB for file uploads
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


